version: '3.9'
services:
  postgresql:
    image: postgres:14-alpine
    restart: on-failure
    ports:
      - "6666:5432"
    volumes:
      - "./data/postgresql:/var/lib/postgresql:delegated"
    environment:
      - "POSTGRES_PASSWORD=secret"
