version: '2.4'
services:
  postgresql:
    image: postgres:9.6-alpine
    restart: on-failure
    ports:
    - "6666:5432"
    volumes:
    - "./data/postgresql:/var/lib/postgresql:rw"
    environment:
      - "POSTGRES_PASSWORD=secret"
