version: '3.9'
services:
  postgresql:
    image: postgres:16-alpine
    restart: on-failure
    ports:
      - "6666:5432"
    volumes:
      - "postgresql-data:/var/lib/postgresql"
    environment:
      - "POSTGRES_PASSWORD=secret"
volumes:
  postgresql-data:
